### ISSUE TITLE
Change base.php

### ISSUE THREAD

**Issue by Val0rous** [val0rant/WebDev-Project#2]
Put html head in all normal files and remove it from base.php, leaving only the body skeleton inside of it. The normal files will then import the necessary css. Other than this, it's not gonna be possible to include additional css or javascript in a web page, and that's why we need to put in templates the necessary things only.

**Comment by val0rant** [comment]
Solved: we can put an arbitrary number of parameters (a.k.a. files) in both css and js templateParams by using a foreach

**Comment by Val0rous** [comment]
Solved: we can put an arbitrary number of parameters (a.k.a. files) in both css and js templateParams by using a foreach
